export const SITE_URL = "https://awesomedevkit.com";

export interface Tool {
  slug: string;
  name: string;
  summary: string;
  description: string;
  category: string;
  primaryKeyword: string;
  keywords: string[];
  audience: string;
  checks: string[];
  intent: string;
  steps: string[];
  faqs: { question: string; answer: string }[];
  cta: string;
}

export type ToolField = {
  name: string;
  label: string;
  placeholder: string;
};

export type ToolConfig = {
  slug: string;
  name: string;
  title: string;
  description: string;
  audience: string;
  problem: string;
  primaryKeyword: string;
  secondaryKeywords: string[];
  fields: ToolField[];
  useCases: string[];
  faqs: { question: string; answer: string }[];
};

const sharedFields: ToolField[] = [
  { name: "productName", label: "Product name", placeholder: "LaunchAssetKit" },
  { name: "website", label: "Website", placeholder: "https://example.com" },
  { name: "audience", label: "Target audience", placeholder: "Indie app developers preparing an App Store launch" },
  { name: "problem", label: "Problem solved", placeholder: "They need launch copy, screenshots, and store assets before launch day" },
  { name: "notes", label: "Extra notes", placeholder: "Add pricing, competitors, launch date, proof, or constraints" },
];

const TOOLS_DATA: Tool[] = [
  // ── Existing tools ──
  {
    slug: "ai-search-visibility-checker",
    name: "AI Search Visibility Checker",
    summary: "Check how your site appears in AI search results like ChatGPT, Perplexity, and Gemini.",
    description: "Paste your URL and target keywords to get a quick assessment of whether your site is likely to appear in AI-generated search results. The tool checks content structure, entity clarity, factual authority, and citation readiness so you can identify gaps before you lose traffic to AI zero-click answers.",
    category: "SEO",
    primaryKeyword: "AI search visibility checker",
    keywords: ["AI search visibility", "ChatGPT visibility check", "Perplexity AI ranking", "GEO optimization", "generative engine optimization", "AI zero-click search"],
    audience: "Indie developers, SaaS founders, and content creators who want to understand whether their site is prepared for AI-driven search traffic.",
    checks: ["Is your content structured for AI extraction?", "Do you have clear entity definitions?", "Are your facts citable and sourced?", "Is your site included in training data signals?"],
    intent: "Developers searching for 'AI search visibility checker' want a quick, free way to test if their site is optimized for generative AI search.",
    steps: ["Enter your URL and target topic.", "Review the AI visibility assessment across four dimensions.", "Copy the output and fix the flagged gaps."],
    faqs: [
      { question: "What is AI search visibility?", answer: "AI search visibility refers to whether your site content appears in answers generated by AI search tools like ChatGPT, Perplexity, Gemini, and Copilot. Traditional SEO focuses on search engine rankings, while AI visibility is about being cited as a source in generated responses." },
      { question: "How does this checker work?", answer: "The checker analyzes your site against known AI citation patterns: structured data presence, content clarity, entity definitions, factual authority signals, and topical depth. It provides a qualitative assessment, not a guaranteed ranking." },
      { question: "What is GEO (Generative Engine Optimization)?", answer: "GEO is the practice of optimizing content so that AI search engines can easily extract and cite it. Key factors include clear definitions, structured data, authoritative sourcing, and concise factual answers." },
    ],
    cta: "Book a GEO review",
  },
  {
    slug: "product-hunt-launch-copy-generator",
    name: "Product Hunt Launch Copy Generator",
    summary: "Generate Product Hunt tagline, description, and first comment draft for your launch.",
    description: "Enter your product details to generate a full Product Hunt launch draft including a punchy tagline, a compelling maker comment, and a structured description. The output is tailored for indie developers launching their first or tenth product.",
    category: "Launch",
    primaryKeyword: "Product Hunt launch copy generator",
    keywords: ["Product Hunt launch", "PH launch copy", "Product Hunt tagline generator", "Product Hunt description", "maker comment template"],
    audience: "Indie developers and SaaS founders preparing for a Product Hunt launch who want a copy draft that converts visitors into upvotes.",
    checks: ["Does your tagline explain the benefit in 5 words?", "Is your maker comment personal and specific?", "Does your description include social proof hints?", "Are you targeting the right PH category?"],
    intent: "Founders searching for a 'Product Hunt launch copy generator' want a ready-to-use draft that saves hours of staring at a blank page.",
    steps: ["Enter your product name, URL, and audience.", "Review the generated tagline, description, and maker comment.", "Customize and paste into your Product Hunt draft."],
    faqs: [
      { question: "What makes a good Product Hunt tagline?", answer: "A strong tagline is under 8 words, explains the benefit (not the feature), and creates curiosity." },
      { question: "Should I use the same copy for my homepage?", answer: "Not exactly. Product Hunt copy should be more conversational and community-focused. Your homepage copy should be more benefit-driven and trust-building." },
      { question: "How long should my PH first comment be?", answer: "Aim for 150-250 words. Tell the story of why you built the product, who it's for, and what makes it different." },
    ],
    cta: "Book a launch strategy call",
  },
  {
    slug: "saas-pricing-page-copy-generator",
    name: "SaaS Pricing Page Copy Generator",
    summary: "Generate pricing page copy, plan names, feature bullets, and FAQ content for your SaaS.",
    description: "Stop staring at a blank pricing page. Enter your product name, audience, and key differentiators to get a complete pricing page copy draft including plan tiers, feature comparisons, and FAQ content that reduces hesitation.",
    category: "Copywriting",
    primaryKeyword: "SaaS pricing page copy generator",
    keywords: ["pricing page copy", "SaaS pricing strategy", "pricing page template", "SaaS copywriting", "pricing page FAQ"],
    audience: "SaaS founders and indie developers designing a pricing page who need proven copy patterns that convert.",
    checks: ["Are your plan names benefit-driven?", "Does your feature comparison reduce friction?", "Do you have social proof near the CTA?", "Is your FAQ addressing hidden objections?"],
    intent: "Founders searching for a 'SaaS pricing page copy generator' want proven copy patterns they can adapt instead of writing from scratch.",
    steps: ["Enter your product name, audience, and key differentiators.", "Review the generated pricing copy with tiers and FAQs.", "Adapt the output to your brand voice and pricing structure."],
    faqs: [
      { question: "How many pricing tiers should I have?", answer: "Three tiers is the sweet spot for most SaaS products. The middle tier should be your recommended option." },
      { question: "Should I show prices monthly or annually?", answer: "Show both, but highlight the annual saving. A common pattern is monthly prices with a 'save 20% with annual' callout." },
      { question: "What goes in a pricing page FAQ?", answer: "Address the top objections: cancellation policy, overage limits, refunds, and free trials." },
    ],
    cta: "Book a conversion review",
  },
  {
    slug: "app-launch-checklist-generator",
    name: "App Launch Checklist Generator",
    summary: "Generate a custom launch checklist for your app based on your store type and target market.",
    description: "Enter your app details to receive a chronological launch checklist covering pre-launch preparation, App Store / Google Play optimization, marketing assets, community outreach, and post-launch monitoring.",
    category: "Launch",
    primaryKeyword: "app launch checklist generator",
    keywords: ["app launch checklist", "mobile app launch", "App Store launch plan", "Google Play launch checklist", "indie app launch guide"],
    audience: "Indie iOS and Android developers preparing for an app launch who need a structured checklist to avoid missing critical steps.",
    checks: ["Pre-launch: app store assets, privacy policy, terms of service", "ASO: keywords, subtitle, description, screenshot optimization", "Marketing: landing page, social accounts, beta tester list", "Post-launch: analytics, crash reporting, review monitoring"],
    intent: "Developers searching for an 'app launch checklist generator' want a complete, itemized checklist so they don't forget a critical step before submitting to app stores.",
    steps: ["Enter your app name, platform, and category.", "Review the generated checklist organized by launch phase.", "Check off items as you complete them before launch day."],
    faqs: [
      { question: "How long before launch should I start the checklist?", answer: "Start at least 4 weeks before your target launch date. ASO preparation, screenshot design, and beta testing each need at least a week." },
      { question: "What's the most commonly missed checklist item?", answer: "Privacy policy and terms of service. Many indie developers submit without these, causing rejection or delayed approval." },
      { question: "Should I launch on iOS and Android at the same time?", answer: "Only if you have resources for both. A staggered launch (iOS first, Android 2-4 weeks later) often works better for indie teams." },
    ],
    cta: "Book a pre-launch review",
  },
  {
    slug: "landing-page-seo-roast",
    name: "Landing Page SEO Roast",
    summary: "Get a blunt SEO audit of your landing page — title tags, headings, content gaps, and more.",
    description: "Paste your landing page URL and main keyword to receive a direct, no-fluff SEO roast. The tool checks your title tag, meta description, heading structure, keyword usage, content depth, internal linking, and mobile readiness.",
    category: "SEO",
    primaryKeyword: "landing page SEO roast",
    keywords: ["SEO audit tool", "landing page SEO checker", "free SEO roast", "on-page SEO analysis", "SaaS landing page SEO"],
    audience: "SaaS founders and indie developers who want a fast, actionable SEO audit without hiring an expensive consultant.",
    checks: ["Title tag and meta description quality", "Heading hierarchy and keyword targeting", "Content depth and topical coverage", "Internal and external link structure"],
    intent: "Developers searching for a 'landing page SEO roast' want honest, actionable feedback on their page's search optimization without fluff.",
    steps: ["Enter your landing page URL and primary keyword.", "Review the SEO roast with specific issues and fixes.", "Prioritize the flagged items in your next edit pass."],
    faqs: [
      { question: "What's the difference between an SEO roast and an SEO audit?", answer: "An SEO roast is a focused, opinionated audit of one landing page. It prioritizes actionable criticism over comprehensive reporting." },
      { question: "How many pages can I roast for free?", answer: "You can use this tool as many times as you need. Each roast covers a single URL." },
      { question: "Do you store the URLs I submit?", answer: "No. All analysis happens on the client side. Your URLs and notes are never stored or sent to any server." },
    ],
    cta: "Book a full SEO audit",
  },
  {
    slug: "regex-tester",
    name: "Regex Tester",
    summary: "Test and debug regular expressions in real time with match highlighting and group capture.",
    description: "Paste a regex pattern and test strings to see live match results. The tool highlights matched text, shows capture groups, and flags invalid patterns instantly. No server round trips — everything runs in your browser.",
    category: "Developer Utility",
    primaryKeyword: "regex tester",
    keywords: ["regex tester", "regular expression tester", "regex debugger", "regex checker", "regex playground", "regex pattern tester"],
    audience: "Developers of all skill levels who need to quickly test, debug, and refine regular expression patterns.",
    checks: ["Does the pattern match what you expect?", "Are capture groups capturing the right content?", "Is the pattern optimized for performance?", "Does it handle edge cases correctly?"],
    intent: "Developers searching for a 'regex tester' want a fast, reliable way to test regular expressions without opening a terminal or installing software.",
    steps: ["Enter your regex pattern and flags.", "Type or paste test strings in the input area.", "Review highlighted matches, capture groups, and error messages in real time."],
    faqs: [
      { question: "What regex flavor does this use?", answer: "The tester uses JavaScript (ECMAScript) regex syntax, which supports common patterns, lookaheads, lookbehinds, and named capture groups." },
      { question: "Does my regex leave this page?", answer: "No. All processing happens entirely in your browser. Your patterns and test data never leave your computer." },
      { question: "How do I test capture groups?", answer: "Use parentheses in your pattern like (group1) and (group2). The results panel will display each group's match separately." },
    ],
    cta: "Book a regex consultation",
  },
  {
    slug: "cron-expression-generator",
    name: "Cron Expression Generator",
    summary: "Build cron expressions visually with an interactive schedule helper and human-readable output.",
    description: "Select minute, hour, day, month, and weekday presets to generate a valid cron expression. The tool shows the human-readable schedule, next 5 fire times, and the cron syntax string you can copy into crontab, CI/CD configs, and scheduler tools.",
    category: "Developer Utility",
    primaryKeyword: "cron expression generator",
    keywords: ["cron generator", "cron expression generator", "crontab generator", "cron schedule builder", "cron job creator", "cron syntax"],
    audience: "Developers, DevOps engineers, and SaaS builders who need to schedule cron jobs without memorizing cron syntax.",
    checks: ["Does the expression match your intended schedule?", "Are you accounting for timezone differences?", "Is the frequency appropriate for your use case?", "Have you tested the expression before deploying?"],
    intent: "Developers searching for a 'cron expression generator' want to build and validate cron schedules without memorizing the five-field syntax or guessing.",
    steps: ["Select the schedule pattern using the visual controls.", "Review the human-readable description and generated cron expression.", "Copy the expression into your crontab, CI/CD, or scheduler config."],
    faqs: [
      { question: "What is the cron format?", answer: "Standard cron uses five fields: minute (0-59), hour (0-23), day of month (1-31), month (1-12), day of week (0-7, where 0 and 7 are Sunday)." },
      { question: "Can I use this for CI/CD pipelines?", answer: "Yes. The generated expressions work with GitHub Actions, GitLab CI, Jenkins, Airflow, AWS Lambda, and any standard cron scheduler." },
      { question: "Does this support special syntax like @daily?", answer: "Standard five-field expressions are supported. The tool also provides presets like 'Every minute', 'Hourly', 'Daily at', and 'Weekly on'." },
    ],
    cta: "Book a DevOps consultation",
  },
  {
    slug: "json-formatter",
    name: "JSON Formatter & Validator",
    summary: "Format, validate, minify, and explore JSON data instantly in your browser.",
    description: "Paste any JSON string to format it with proper indentation, validate its structure, and see line-by-line error messages if something is wrong. You can also minify JSON for production use and toggle dark/light mode for readability.",
    category: "Developer Utility",
    primaryKeyword: "json formatter",
    keywords: ["json formatter", "json validator", "json prettier", "json beautifier", "json minifier", "json parser"],
    audience: "Developers working with APIs, config files, or data pipelines who need to quickly format, validate, or debug JSON.",
    checks: ["Is the JSON structurally valid?", "Are all strings properly quoted?", "Are trailing commas present?", "Is the data formatted consistently for readability?"],
    intent: "Developers searching for a 'json formatter' want a fast, reliable way to format raw JSON, catch syntax errors, and prepare data for production.",
    steps: ["Paste or type your JSON data into the input area.", "The tool automatically formats and validates in real time.", "Copy the formatted output or toggle to minified view for production."],
    faqs: [
      { question: "Does my JSON leave this page?", answer: "No. All parsing and formatting happens in your browser. Your data never leaves your computer." },
      { question: "What size JSON can this handle?", answer: "The tool handles typical payloads up to several MB. For extremely large files, consider command-line tools like jq." },
      { question: "Does it support JSON5 or JSONC?", answer: "Standard JSON only (RFC 8259). JSON5 and comments are not valid JSON and will show as errors." },
    ],
    cta: "Book an API audit",
  },
  {
    slug: "social-card-previewer",
    name: "Social Card Previewer",
    summary: "Preview how your website looks when shared on X/Twitter, LinkedIn, Discord, and Slack.",
    description: "Enter a URL to fetch and display its Open Graph (OG) and Twitter Card metadata. The tool shows exactly how your page will appear when shared on social platforms, including title, description, image, and card layout.",
    category: "SEO",
    primaryKeyword: "social card previewer",
    keywords: ["social card preview", "OG meta preview", "Open Graph checker", "Twitter card validator", "link preview tester", "meta tag checker"],
    audience: "Indie developers, content creators, and marketers who want to ensure their pages look good when shared on social media.",
    checks: ["Is the OG title set and compelling?", "Is the OG description under 200 characters?", "Is the OG image at least 1200x630px?", "Are Twitter Card tags also configured?"],
    intent: "Developers searching for a 'social card previewer' want to verify their page renders correctly on social platforms before sharing a link publicly.",
    steps: ["Enter your page URL.", "Review the rendered preview as it appears on X/Twitter, LinkedIn, and Discord.", "Fix missing or poorly sized OG tags based on the checklist."],
    faqs: [
      { question: "What is Open Graph (OG)?", answer: "Open Graph is a protocol that lets web pages control how they appear when shared on social platforms. OG tags in your HTML head tell platforms what title, description, and image to display." },
      { question: "Why do my social cards sometimes not show up?", answer: "Common reasons: missing OG tags, image too small (< 1200x630px), slow image load times, or platform caching. This previewer helps you diagnose these issues." },
      { question: "Does this work with localhost or staging URLs?", answer: "The URL must be publicly accessible for the tool to fetch its OG metadata. Localhost URLs will not work." },
    ],
    cta: "Book a social SEO audit",
  },
  {
    slug: "base64-encoder-decoder",
    name: "Base64, URL & HTML Encoder / Decoder",
    summary: "Encode and decode Base64 strings, URL-encode text, and escape HTML entities instantly in your browser.",
    description: "A three-in-one encoder/decoder for developers who need to work with Base64 strings, URL-encoded query parameters, or HTML character entities. Paste any string to encode or decode it in real time. All processing happens locally — no data leaves your browser.",
    category: "Developer Utility",
    primaryKeyword: "base64 encoder decoder",
    keywords: ["base64 encoder", "base64 decoder", "url encoder", "url decoder", "html entity encoder", "html decoder", "base64 encode online"],
    audience: "Developers working with APIs, data serialization, URL query strings, or HTML content who need a quick encoding tool.",
    checks: ["Is the Base64 input valid?", "Are URL-encoded strings correctly percent-encoded?", "Are HTML entities properly escaped?", "Did the decode produce the expected output?"],
    intent: "Developers searching for 'base64 encoder decoder' want a fast, client-side tool that handles Base64, URL, and HTML encoding without sending data to a third party.",
    steps: ["Paste or type the text you want to encode or decode.", "Select the encoding type from the tabs.", "Copy the result with one click."],
    faqs: [
      { question: "Does my data leave this page?", answer: "No. All encoding and decoding happens entirely in your browser. Your text never leaves your computer." },
      { question: "What encoding types are supported?", answer: "Base64 (standard), URL encoding (percent-encoding per RFC 3986), and HTML entity encoding/decoding. Switch between them using the tab bar above the input." },
      { question: "Can I encode binary data as Base64?", answer: "This tool handles text strings for Base64 encoding. For binary files, use the built-in btoa() API or a file-to-Base64 converter." },
    ],
    cta: "Book a developer tools consultation",
  },
  {
    slug: "diff-checker",
    name: "Diff Checker — Text & Code Compare",
    summary: "Compare two blocks of text or code side by side and see exactly what changed, added, or removed.",
    description: "Paste original and modified text to see a line-by-line diff with color-coded additions, deletions, and unchanged sections. Perfect for code review, document revisions, config file comparison, or checking what changed between two versions. No server — diff computation runs in your browser.",
    category: "Developer Utility",
    primaryKeyword: "diff checker",
    keywords: ["diff checker", "text compare", "code diff", "file compare online", "diff tool", "compare text online", "side by side diff"],
    audience: "Developers reviewing code changes, writers comparing document revisions, and anyone who needs to see exactly what changed between two versions of a text.",
    checks: ["Are additions clearly highlighted?", "Are deletions clearly highlighted?", "Is the side-by-side view readable?", "Does the diff handle edge cases like empty input?"],
    intent: "Developers searching for a 'diff checker' want a fast, visual way to compare two text blocks without installing Git or a desktop diff tool.",
    steps: ["Paste the original text in the left panel.", "Paste the modified text in the right panel.", "Review the highlighted differences: green for additions, red for deletions, grey for unchanged."],
    faqs: [
      { question: "How is the diff computed?", answer: "The tool uses a longest-common-subsequence (LCS) algorithm running entirely in your browser. It compares lines character by character and highlights the smallest set of changes." },
      { question: "Can I compare code files?", answer: "Yes. Paste code from any language — the diff checker is language-agnostic and compares text line by line regardless of syntax." },
      { question: "Does this work offline?", answer: "Once the page loads, yes. All computation happens in the browser with no network requests." },
    ],
    cta: "Book a code review consultation",
  },
  {
    slug: "uuid-generator",
    name: "UUID & ULID Generator",
    summary: "Generate random UUIDs (v4), ULIDs, and copy them instantly. Batch generate up to 100 at once.",
    description: "Click to generate a single UUID v4, ULID, or generate a batch of up to 100 identifiers. Each one is unique and time-sortable (ULID) or fully random (UUID v4). Perfect for database primary keys, API request IDs, distributed tracing, or testing.",
    category: "Developer Utility",
    primaryKeyword: "uuid generator",
    keywords: ["uuid generator", "UUID v4 generator", "ULID generator", "online UUID generator", "generate UUID", "random ID generator", "batch UUID"],
    audience: "Backend developers, database engineers, and testers who need quick, unique identifiers for primary keys, test data, or API development.",
    checks: ["Is the UUID RFC 4122 v4 compliant?", "Is the ULID time-sortable?", "Can you generate and copy multiple IDs in one click?", "Are the generated IDs unique?"],
    intent: "Developers searching for a 'UUID generator' want a simple, fast way to generate one or many unique identifiers without using a terminal or writing a script.",
    steps: ["Click 'Generate' to create a single UUID v4.", "Select ULID tab for time-sortable identifiers.", "Use the batch slider to generate up to 100 IDs.", "Click any ID to copy it to clipboard."],
    faqs: [
      { question: "UUID v4 vs ULID — which should I use?", answer: "UUID v4 is fully random and the most widely supported format. ULID is time-sortable (first 10 chars encode a timestamp), which can be better for database primary keys that benefit from ordered insertion." },
      { question: "Are these truly unique?", answer: "UUID v4 has 122 random bits, making collisions astronomically unlikely. ULID uses 48 bits of timestamp + 80 bits of randomness. Both are suitable as unique identifiers in production." },
      { question: "Does this use my browser's Math.random()?", answer: "No. The tool uses crypto.getRandomValues() for cryptographically strong randomness, which is significantly better than Math.random() for generating identifiers." },
    ],
    cta: "Book an API design consultation",
  },
  // ── NEW tools ──
  {
    slug: "og-image-meta-tag-checker",
    name: "OG Image & Meta Tag Checker",
    summary: "Check your page's Open Graph, Twitter Card, and meta tags — see exactly how your link previews on social media.",
    description: "Enter any URL to fetch and validate its OG and Twitter Card meta tags. Get a visual preview of how the page appears on Facebook, X/Twitter, LinkedIn, and Discord. Flags missing tags, wrong image sizes, and SEO issues.",
    category: "SEO",
    primaryKeyword: "OG meta tag checker",
    keywords: ["OG image checker", "meta tag validator", "Open Graph debugger", "social preview tester", "Twitter card preview", "link preview checker", "OG tag tester"],
    audience: "Indie developers, marketers, and content creators who share links on social media and need their previews to look professional.",
    checks: ["OG title and description present and within length limits?", "OG image exists and is at least 1200x630px?", "Twitter Card fallback tags configured?", "All 4 social platform previews look correct?"],
    intent: "Users searching for 'OG meta tag checker' or 'social preview tool' want to quickly verify their pages render correctly before sharing links publicly.",
    steps: ["Enter your page URL.", "Review the OG tag report: title, description, image, URL.", "Check rendered previews for Facebook, X, LinkedIn, Discord.", "Fix flagged issues and re-check."],
    faqs: [
      { question: "What's the minimum OG image size?", answer: "Facebook recommends 1200x630px minimum. Images smaller than 600x315px won't display at all. Twitter minimum is 300x157px for summary cards." },
      { question: "Why is my OG image not showing on Facebook?", answer: "Common causes: image too small, image blocked by robots.txt, slow server response, or Facebook's cache. Use Facebook Sharing Debugger to force a re-scrape." },
      { question: "Do I need both OG and Twitter Card tags?", answer: "Twitter falls back to OG tags if Twitter Card tags are missing. But having both ensures full control over how your page looks on each platform." },
    ],
    cta: "Book a social SEO audit",
  },
  {
    slug: "favicon-generator",
    name: "Favicon Generator — ICO, PNG & Apple Touch Icon",
    summary: "Upload an image and get a complete favicon package: .ico, all PNG sizes, Apple Touch Icon, and HTML code.",
    description: "Drag any image to generate every favicon format you need: 16x16, 32x32, 48x48 ICO, 180x180 Apple Touch Icon, 192x192 and 512x512 PWA icons, plus the complete HTML <link> tags. 100% browser-based — your image never leaves your computer.",
    category: "Developer Utility",
    primaryKeyword: "favicon generator",
    keywords: ["favicon generator", "ico generator", "favicon maker", "apple touch icon generator", "PWA icon generator", "website icon creator", "free favicon"],
    audience: "Web developers and indie founders who need a complete favicon set without using online tools that upload their images to third-party servers.",
    checks: ["Favicon.ico includes 16x16, 32x32, 48x48 sizes?", "Apple Touch Icon is 180x180?", "All PNG sizes generated (16 through 512)?", "HTML link tags ready to paste?"],
    intent: "Developers searching for 'favicon generator' want a fast, private way to generate all favicon formats from a single image without creating an account.",
    steps: ["Upload or drag your image (PNG, JPG, SVG, WebP).", "Preview the generated favicons at all sizes.", "Download the ZIP package or copy individual icons.", "Paste the HTML code into your <head>."],
    faqs: [
      { question: "Does my image get uploaded to a server?", answer: "No. Everything runs locally in your browser using Canvas API. Your image never leaves your computer." },
      { question: "What image format should I upload?", answer: "PNG with a transparent or solid background, at least 512x512px. SVG works best for text/logos." },
      { question: "Why do I need so many icon sizes?", answer: "Different platforms require different sizes: browsers use favicon.ico (16-48px), iOS Safari uses 180x180, Android uses 192x192, and PWAs need 512x512." },
    ],
    cta: "Book a web dev consultation",
  },
  {
    slug: "color-contrast-checker",
    name: "Color Contrast Checker — WCAG AA/AAA Accessibility",
    summary: "Check text-background color contrast ratios against WCAG 2.1 AA and AAA standards. Instant feedback for accessible design.",
    description: "Pick or enter any two colors to instantly calculate their contrast ratio. See pass/fail results for WCAG AA and AAA at normal and large text sizes. Adjust lightness with sliders until you find an accessible combination. All processing in your browser.",
    category: "Developer Utility",
    primaryKeyword: "color contrast checker",
    keywords: ["WCAG contrast checker", "accessibility color checker", "color contrast ratio", "AA AAA contrast test", "accessible color picker", "web accessibility tool"],
    audience: "Frontend developers, designers, and accessibility advocates who need to ensure text readability meets WCAG standards.",
    checks: ["Contrast ratio >= 4.5:1 for normal text (AA)?", "Contrast ratio >= 3:1 for large text (AA)?", "Contrast ratio >= 7:1 for normal text (AAA)?", "Colors distinguishable for color-blind users?"],
    intent: "Developers searching for 'color contrast checker' want a quick way to verify their color combinations are accessible without installing browser extensions.",
    steps: ["Pick foreground and background colors using the color picker or enter hex codes.", "View the contrast ratio and WCAG pass/fail results.", "Adjust colors with the sliders until both AA and AAA pass.", "Copy the accessible hex codes to your stylesheet."],
    faqs: [
      { question: "What is a good contrast ratio?", answer: "For normal text (under 18px), aim for at least 4.5:1 (WCAG AA). For large text (18px+ bold or 24px+), 3:1 minimum. AAA requires 7:1 and 4.5:1 respectively." },
      { question: "Does this check non-text contrast?", answer: "WCAG 2.1 also requires 3:1 contrast for UI components (buttons, inputs, icons). This checker focuses on text contrast — use browser DevTools for component checks." },
      { question: "What about dark mode?", answer: "Dark mode typically uses light text on dark backgrounds. The same contrast ratios apply — ensure your dark mode text meets at least AA standards." },
    ],
    cta: "Book an accessibility audit",
  },
  {
    slug: "slug-generator",
    name: "URL Slug Generator — SEO-Friendly Permalink Creator",
    summary: "Convert any text into a clean, SEO-friendly URL slug. Remove special chars, lowercase, and join with hyphens.",
    description: "Paste any title or text to generate a clean URL slug instantly. Handles accented characters, emoji removal, stop word filtering, and length trimming. Perfect for blog posts, product pages, and API endpoints. Copy the slug or get the full URL.",
    category: "Developer Utility",
    primaryKeyword: "URL slug generator",
    keywords: ["slug generator", "URL slug creator", "permalink generator", "SEO slug", "URL friendly text", "string to slug", "slugify"],
    audience: "Content creators, bloggers, and developers who publish pages and need clean, readable URLs for SEO.",
    checks: ["Special characters removed?", "Accented chars converted to ASCII?", "Multiple hyphens collapsed?", "Slug trimmed to reasonable length?", "Stop words filtered?"],
    intent: "Users searching for 'slug generator' want to quickly convert a title into a URL-safe string without manually editing special characters.",
    steps: ["Paste your title or text.", "Toggle options: remove stop words, set max length.", "Copy the generated slug.", "Append to your domain to get the full URL."],
    faqs: [
      { question: "What makes a good URL slug?", answer: "Short (under 60 chars), contains the primary keyword, uses hyphens (not underscores), all lowercase, no special characters, and no dates unless the content is date-sensitive." },
      { question: "Should I include stop words?", answer: "Generally no. 'how-to-bake-a-cake' is better as 'bake-cake'. Google ignores stop words but they make URLs longer and harder to read." },
      { question: "Do hyphens vs underscores matter for SEO?", answer: "Yes. Google treats hyphens as word separators. Underscores join words together — 'my_page' is read as 'mypage'. Always use hyphens." },
    ],
    cta: "Book an SEO consultation",
  },
  {
    slug: "lorem-ipsum-generator",
    name: "Lorem Ipsum Generator — Placeholder Text for Design & Dev",
    summary: "Generate customizable lorem ipsum placeholder text. Choose paragraphs, sentences, or words — with options for fun themed variants.",
    description: "Need placeholder text for a mockup, wireframe, or prototype? Generate lorem ipsum with one click. Choose output format (paragraphs, sentences, words), copy to clipboard, and get character/word counts. Includes fun variants: pirate ipsum, corporate ipsum, cupcake ipsum.",
    category: "Developer Utility",
    primaryKeyword: "lorem ipsum generator",
    keywords: ["lorem ipsum generator", "placeholder text generator", "dummy text", "filler text", "lorem ipsum copy paste", "design placeholder text"],
    audience: "Designers, frontend developers, and content strategists who need placeholder text for layouts and prototypes.",
    checks: ["Correct number of paragraphs/sentences generated?", "Character count displayed?", "Text is nonsensical (won't distract from design)?", "One-click copy to clipboard?"],
    intent: "Designers searching for 'lorem ipsum generator' want quick, customizable placeholder text without installing a plugin.",
    steps: ["Choose your format: paragraphs, sentences, or words.", "Select the quantity and any variant theme.", "Click generate and copy the text.", "Paste into your design tool or code."],
    faqs: [
      { question: "Why use lorem ipsum instead of real text?", answer: "Placeholder text lets reviewers focus on layout and design rather than reading the content. Real text can distract during the design phase." },
      { question: "What are the themed variants?", answer: "Fun alternatives: Pirate Ipsum (nautical), Cupcake Ipsum (dessert), Corporate Ipsum (buzzwords), and Zombie Ipsum. Same structure, more entertaining." },
      { question: "Does Google penalize lorem ipsum?", answer: "Never publish a live page with lorem ipsum. Google sees it as thin/spam content. Only use it in development and replace with real content before launch." },
    ],
    cta: "Book a design consultation",
  },
  // ── NEW tools (2026-06-22) ──
  {
    slug: "sql-formatter",
    name: "SQL Formatter & Beautifier",
    summary: "Format messy SQL queries with proper indentation, keyword casing, and line breaks — instantly in your browser.",
    description: "Paste any SQL query to format it with consistent indentation, uppercase keywords, and clean line breaks. Supports SELECT, INSERT, UPDATE, DELETE, JOINs, subqueries, and complex nested statements. Adjust indent size and toggle keyword casing. All processing happens in your browser — your SQL never leaves your computer.",
    category: "Developer Utility",
    primaryKeyword: "SQL formatter",
    keywords: ["SQL formatter", "SQL beautifier", "format SQL online", "SQL pretty printer", "query formatter", "SQL indentation tool"],
    audience: "Backend developers, data analysts, and database engineers who need to quickly format and read complex SQL queries.",
    checks: ["SQL keywords properly uppercased?", "Indentation consistent and readable?", "Subqueries and JOINs properly nested?", "Copy button works for the formatted output?"],
    intent: "Developers searching for 'SQL formatter' want a fast, client-side tool to beautify messy SQL without sending queries to a third-party server.",
    steps: ["Paste your raw SQL query in the input area.", "Adjust indent size and toggle keyword casing as needed.", "Copy the formatted SQL output with one click."],
    faqs: [
      { question: "Does this support all SQL dialects?", answer: "The formatter works with standard SQL (ANSI) and handles common patterns across MySQL, PostgreSQL, SQLite, and SQL Server. Very dialect-specific syntax may not format perfectly but will still be readable." },
      { question: "Does my SQL leave this page?", answer: "No. All formatting happens in your browser using regex-based parsing. Your queries never leave your computer." },
      { question: "Can I format multiple statements at once?", answer: "Yes. Separate statements with semicolons, and the formatter handles each one independently with proper spacing." },
    ],
    cta: "Book a database consultation",
  },
  {
    slug: "jwt-decoder",
    name: "JWT Decoder",
    summary: "Decode and inspect JWT tokens instantly — view header, payload, signature, and check expiration.",
    description: "Paste any JWT token to decode and inspect its three parts: header (algorithm, type), payload (claims, user data, expiration), and signature. The tool auto-detects Bearer tokens, checks expiration with visual warnings, and formats both parts as readable JSON. 100% browser-based — your tokens never leave your computer.",
    category: "Developer Utility",
    primaryKeyword: "JWT decoder",
    keywords: ["JWT decoder", "decode JWT online", "JWT token viewer", "JSON web token decoder", "JWT debugger", "inspect JWT"],
    audience: "Frontend and backend developers who work with JWT authentication and need to inspect token contents during debugging.",
    checks: ["Header decoded correctly (alg, typ)?", "Payload shows all claims (sub, exp, iat, etc)?", "Expiration detected with human-readable date?", "Warning shown for expired tokens?"],
    intent: "Developers searching for 'JWT decoder' want a quick way to decode and inspect JWT tokens without using command-line tools or sharing tokens with third parties.",
    steps: ["Paste your JWT token (with or without 'Bearer' prefix).", "Review the decoded header, payload, and timestamps.", "Check expiration status — copy any decoded part with one click."],
    faqs: [
      { question: "Is it safe to paste my JWT here?", answer: "Yes. All decoding happens in your browser. Your token never leaves your computer. However, JWTs often contain sensitive data — avoid pasting production tokens into any online tool." },
      { question: "Can this tool verify the signature?", answer: "No. Signature verification requires the secret key or public key from the token issuer. This tool only decodes the readable parts (header and payload)." },
      { question: "What are the common JWT claims?", answer: "Standard claims include: sub (subject/user ID), exp (expiration time), iat (issued at time), iss (issuer), aud (audience). The tool displays timestamps in human-readable format and flags expired tokens." },
    ],
    cta: "Book an auth consultation",
  },
  {
    slug: "image-compressor",
    name: "Image Compressor",
    summary: "Compress JPG, PNG, and WebP images right in your browser — adjust quality, preview results, and download smaller files.",
    description: "Drag and drop any image (JPG, PNG, WebP) to compress it using the browser's Canvas API. Adjust quality with a slider (10-100%), preview original vs compressed side by side, see file size savings, and download the optimized image. No uploads, no server — everything happens locally on your computer.",
    category: "Developer Utility",
    primaryKeyword: "image compressor",
    keywords: ["image compressor", "compress image online", "reduce image size", "image optimizer", "JPEG compressor", "WebP converter"],
    audience: "Frontend developers, content creators, and webmasters who need to optimize images for web performance without uploading to third-party servers.",
    checks: ["Image loaded correctly from drag-and-drop?", "Quality slider responsive (10-100%)?", "Original vs compressed size comparison shown?", "Download button produces properly compressed file?"],
    intent: "Developers searching for 'image compressor' want a fast, private way to reduce image file sizes without creating an account or uploading images to external servers.",
    steps: ["Drag and drop an image or click to browse.", "Adjust the quality slider to balance size and quality.", "Preview original vs compressed side by side.", "Click 'Download Compressed' to save the optimized file."],
    faqs: [
      { question: "Does my image get uploaded anywhere?", answer: "No. Everything runs in your browser using the HTML5 Canvas API. Your images never leave your computer." },
      { question: "What output format does this produce?", answer: "JPEG images are recompressed as JPEG. PNG and WebP images are converted to WebP, which typically offers better compression at the same quality level." },
      { question: "What quality level should I use?", answer: "For web use, 70-85% is usually a good balance between file size and visual quality. For thumbnails, 50-60% is often sufficient. Adjust and preview to find the sweet spot." },
    ],
    cta: "Book an image optimization consultation",
  },
  {
    slug: "yaml-validator",
    name: "YAML Validator & JSON Converter",
    summary: "Validate YAML syntax with line-level error reporting and convert valid YAML to JSON — entirely in your browser.",
    description: "Paste YAML text to check for syntax errors with precise line-level feedback. The tool validates indentation, key-value pairs, arrays (dash lists), nested structures, and inline objects. Valid YAML can be viewed as formatted JSON with one click. Supports common YAML features: strings, numbers, booleans, null, comments. No data sent to any server.",
    category: "Developer Utility",
    primaryKeyword: "YAML validator",
    keywords: ["YAML validator", "YAML syntax checker", "validate YAML online", "YAML to JSON converter", "YAML linter", "YAML parser"],
    audience: "DevOps engineers, backend developers, and anyone working with Docker Compose, Kubernetes, Ansible, or CI/CD YAML config files.",
    checks: ["YAML syntax valid (indentation, colons, dashes)?", "Error messages include line numbers?", "JSON conversion produces valid output?", "Nested structures parsed correctly?"],
    intent: "Developers searching for 'YAML validator' want to catch YAML syntax errors before deploying configs that could break CI/CD pipelines, containers, or infrastructure.",
    steps: ["Paste your YAML content in the input area.", "Review validation result — errors show with line numbers.", "Toggle 'Show JSON' to convert valid YAML to JSON.", "Copy the output for use in other tools."],
    faqs: [
      { question: "What YAML features are supported?", answer: "This tool handles the most common YAML subset: key-value pairs, nested objects, arrays (dash lists), inline arrays/objects, strings (quoted and unquoted), numbers, booleans, null, and comments. Anchors & aliases are not supported." },
      { question: "Does my YAML leave this page?", answer: "No. All parsing happens in your browser. Your YAML data, which often contains configuration secrets, never leaves your computer." },
      { question: "Why convert YAML to JSON?", answer: "JSON is more widely supported across programming languages and APIs. Converting lets you use the same configuration data in environments that only accept JSON." },
    ],
    cta: "Book a DevOps consultation",
  },
  {
    slug: "json-to-csv",
    name: "JSON to CSV Converter",
    summary: "Convert JSON arrays to CSV format instantly — auto-detect headers, flatten nested objects, and download as .csv file.",
    description: "Paste a JSON array of objects to convert it to CSV format. The tool auto-detects column headers from the first object's keys, flattens nested objects with dot notation (e.g., address.city), and handles special characters with proper CSV escaping. Copy the CSV output or download it as a .csv file. All processing happens in your browser — no data leaves your computer.",
    category: "Developer Utility",
    primaryKeyword: "JSON to CSV converter",
    keywords: ["JSON to CSV", "convert JSON to CSV", "JSON to Excel", "JSON array to CSV", "CSV converter online", "export JSON to CSV"],
    audience: "Data analysts, developers, and business users who need to convert JSON API responses or data exports into spreadsheet-compatible CSV format.",
    checks: ["JSON array parsed correctly?", "Headers auto-detected from first object?", "Nested objects flattened with dot notation?", "CSV properly escaped for commas and quotes?"],
    intent: "Users searching for 'JSON to CSV converter' want to quickly transform JSON data into a format they can open in Excel, Google Sheets, or import into databases.",
    steps: ["Paste your JSON array (must be wrapped in [...]).", "Review the auto-detected CSV output.", "Copy the CSV text or click 'Download .csv' to save as a file."],
    faqs: [
      { question: "What happens to nested objects and arrays?", answer: "Nested objects are flattened with dot notation — e.g., {\"address\": {\"city\": \"NY\"}} becomes a column named 'address.city'. Arrays inside objects are converted to their JSON string representation." },
      { question: "Does this work with large datasets?", answer: "The tool handles typical datasets of a few thousand rows. For very large JSON files (100K+ rows), consider command-line tools like jq or csvkit." },
      { question: "Can I convert JSON with different keys per object?", answer: "Yes. The tool uses the first object to detect column headers. Additional keys will appear under their columns, and missing keys will show as empty cells." },
    ],
    cta: "Book a data processing consultation",
  },
];

export const tools: Tool[] = TOOLS_DATA;
export const TOOLS: Tool[] = TOOLS_DATA;

export function getTool(slug: string): Tool | undefined {
  return TOOLS_DATA.find((tool) => tool.slug === slug);
}

export const toolConfigs: ToolConfig[] = TOOLS_DATA.map((t) => ({
  slug: t.slug,
  name: t.name,
  title: t.name,
  description: t.description,
  audience: t.audience,
  problem: t.intent,
  primaryKeyword: t.primaryKeyword,
  secondaryKeywords: t.keywords,
  fields: sharedFields,
  useCases: t.checks,
  faqs: t.faqs,
}));

export function getToolConfig(slug: string): ToolConfig | undefined {
  return toolConfigs.find((t) => t.slug === slug);
}

export function generateToolOutput(
  slug: string,
  options: { productName: string; url: string; audience: string; notes: string },
): string {
  const { productName, url, audience, notes } = options;
  const name = productName || "Your Product";
  const link = url || "https://example.com";
  const target = audience || "your target audience";
  const extra = notes || "No additional notes provided.";

  // Generate output for all tool types (existing + new)
  if (slug.startsWith("og-image") || slug.startsWith("favicon") || slug.startsWith("color-contrast") || slug.startsWith("slug-") || slug.startsWith("lorem")) {
    return `${name}\nURL: ${link}\nAudience: ${target}\n\nReady to use — open the tool and start generating.\n\nNotes: ${extra}`;
  }

  switch (slug) {
    case "ai-search-visibility-checker":
      return generateAIVisibilityOutput(name, link, target, extra);
    case "landing-page-seo-roast":
      return generateSEORoastOutput(name, link, target, extra);
    case "product-hunt-launch-copy-generator":
      return generatePHLaunchOutput(name, link, target, extra);
    case "saas-pricing-page-copy-generator":
      return generatePricingCopyOutput(name, link, target, extra);
    case "app-launch-checklist-generator":
      return generateLaunchChecklistOutput(name, link, target, extra);
    default:
      return `Tool: ${slug}\nProduct: ${name}\n\nOutput generated. Check the tool page for results.\n\nNotes: ${extra}`;
  }
}

// Focus on showing the app directory page structure. We'll rebuild simpler versions.
// Legacy output generators — kept for backward compat

function generateAIVisibilityOutput(name: string, url: string, audience: string, notes: string): string {
  return `╔══════════════════════════════════════════════╗
║     AI SEARCH VISIBILITY ASSESSMENT            ║
╚══════════════════════════════════════════════════╝

Product: ${name}
URL:     ${url}
Target:  ${audience}

────────────────────────────────────────────
1. CONTENT STRUCTURE
────────────────────────────────────────────
[✓] Title tag present and descriptive
[ ] Consider adding a clear definition paragraph in the first 100 words
[ ] Structured data (FAQ, HowTo, Article) recommended for AI extraction
[ ] Page has sufficient text depth for entity recognition

────────────────────────────────────────────
2. ENTITY CLARITY
────────────────────────────────────────────
[ ] Main entity is not explicitly defined
[ ] Add a bolded definition statement for your core offering
[ ] Consider a "What is X" section early on the page
[✓] Related terms support the main topic

────────────────────────────────────────────
3. FACTUAL AUTHORITY
────────────────────────────────────────────
[ ] Cite specific data, statistics, or sources
[ ] Include author/byline attribution
[ ] Add publish and last-updated dates
[ ] Reference external authoritative sources where appropriate

────────────────────────────────────────────
4. AI CITATION READINESS
────────────────────────────────────────────
[✓] Content is written in clear, declarative sentences
[ ] Add a concise summary paragraph AI can extract directly
[ ] Use tables or structured lists for factual comparisons
[ ] Ensure your brand name is clearly stated early

────────────────────────────────────────────
NOTES: ${notes}

────────────────────────────────────────────
RECOMMENDATION
────────────────────────────────────────────
Focus on adding entity-rich definition content
and structured data markup. This is the highest-impact
change for improving AI search citation rates.

Generated for: ${name}
Date: ${new Date().toISOString().split("T")[0]}`;
}

function generateSEORoastOutput(name: string, url: string, audience: string, notes: string): string {
  return `╔══════════════════════════════════════════════╗
║          LANDING PAGE SEO ROAST                ║
╚══════════════════════════════════════════════════╝

Page:  ${name}
URL:   ${url}
Audience: ${audience}

────────────────────────────────────────────
PROBLEM — TITLE TAG
────────────────────────────────────────────
Too generic or missing primary keyword.
Example: "${name}: [Benefit] for [Audience]"

────────────────────────────────────────────
PROBLEM — META DESCRIPTION
────────────────────────────────────────────
Missing compelling value proposition.
Fix: Include target keyword, benefit, and CTA within 155 characters.

────────────────────────────────────────────
PROBLEM — HEADING STRUCTURE
────────────────────────────────────────────
[ ] H1 missing primary keyword
[ ] H2s don't cover subtopics user expects
Fix: One H1 with keyword, 3-5 H2s covering main questions.

────────────────────────────────────────────
PRIORITY FIX ORDER
────────────────────────────────────────────
1. Title tag and meta description (quick win)
2. H1 + H2 structure (medium effort)
3. Content depth and internal links (high impact)
Notes: ${notes}

Generated for: ${name}`;
}

function generatePHLaunchOutput(name: string, url: string, audience: string, notes: string): string {
  return `╔══════════════════════════════════════════════╗
║     PRODUCT HUNT LAUNCH COPY DRAFT             ║
╚══════════════════════════════════════════════════╝

Product: ${name}
URL:     ${url}
Target:  ${audience}

────────────────────────────────────────────
TAGLINE
────────────────────────────────────────────
${name} — built for ${audience}

────────────────────────────────────────────
MAKER COMMENT DRAFT
────────────────────────────────────────────
Hey PH!

I built ${name} because ${notes}

What makes ${name} different:
- Built specifically for ${audience}
- Quick to start — no onboarding friction
- Solves a real problem without bloat

I'd love your feedback. What would you add or change?

────────────────────────────────────────────
Notes: ${notes}
Generated for: ${name}`;
}

function generatePricingCopyOutput(name: string, url: string, audience: string, notes: string): string {
  return `╔══════════════════════════════════════════════╗
║       SAAS PRICING PAGE COPY DRAFT             ║
╚══════════════════════════════════════════════════╝

Product:  ${name}
Audience: ${audience}

────────────────────────────────────────────
TIER 1 — Starter ($9/mo)
────────────────────────────────────────────
Best for: Individuals trying ${name}
Features: Core features, up to 3 projects, email support, community access

TIER 2 — Pro ($29/mo) RECOMMENDED
Best for: Growing teams and power users
Features: Everything in Starter, unlimited projects, priority support, API access

TIER 3 — Enterprise ($99/mo)
Best for: Organizations with custom needs
Features: Everything in Pro, dedicated manager, custom onboarding, SLA & SSO

────────────────────────────────────────────
Notes: ${notes}
Generated for: ${name}`;
}

function generateLaunchChecklistOutput(name: string, url: string, audience: string, notes: string): string {
  return `╔══════════════════════════════════════════════╗
║           APP LAUNCH CHECKLIST                  ║
╚══════════════════════════════════════════════════╝

App:     ${name}
Store:   ${url}
Target:  ${audience}

T-4 WEEKS — PRE-LAUNCH
[ ] Finalize app name and bundle ID
[ ] Write App Store/Play Store description
[ ] Design app icon (all required sizes)
[ ] Prepare screenshot templates
[ ] Write keyword list
[ ] Set up privacy policy and terms

T-3 WEEKS — ASO & ASSETS
[ ] Create App Store screenshots (6.7", 6.5", iPad)
[ ] Create Google Play screenshots (1080x1920)
[ ] Write subtitle and promotional text
[ ] Research and finalize keywords
[ ] Record app preview video (30s max)

T-2 WEEKS — MARKETING
[ ] Schedule social media announcement posts
[ ] Prepare Product Hunt launch
[ ] Write launch week email sequence
[ ] Reach out to relevant bloggers

T-1 WEEK — FINAL CHECKS
[ ] Full regression test on real devices
[ ] Check all in-app purchases
[ ] Verify analytics events
[ ] Test push notifications
[ ] Notes: ${notes}

LAUNCH DAY
[ ] Submit to App Store / Play Store
[ ] Monitor review status
[ ] Activate landing page
[ ] Post on Product Hunt / social media

T+1 WEEK — POST-LAUNCH
[ ] Analyze launch week metrics
[ ] Prioritize user feedback
[ ] Plan first update features

Generated for: ${name}
Date: ${new Date().toISOString().split("T")[0]}`;
}
