export const SITE_URL = "https://awesomedevkit.com";

/* ── Type used by ToolPage + ToolGenerator ── */
export interface Tool {
  slug: string;
  name: string;
  summary: string;
  description: string;
  category: string;
  primaryKeyword: string;
  keywords: string[];
  audience: string;
  checks: string[];
  intent: string;
  steps: string[];
  faqs: { question: string; answer: string }[];
  cta: string;
}

/* ── Original ToolConfig type kept for backward compat ── */
export type ToolField = {
  name: string;
  label: string;
  placeholder: string;
};

export type ToolConfig = {
  slug: string;
  name: string;
  title: string;
  description: string;
  audience: string;
  problem: string;
  primaryKeyword: string;
  secondaryKeywords: string[];
  fields: ToolField[];
  useCases: string[];
  faqs: { question: string; answer: string }[];
};

const sharedFields: ToolField[] = [
  { name: "productName", label: "Product name", placeholder: "LaunchAssetKit" },
  { name: "website", label: "Website", placeholder: "https://example.com" },
  { name: "audience", label: "Target audience", placeholder: "Indie app developers preparing an App Store launch" },
  { name: "problem", label: "Problem solved", placeholder: "They need launch copy, screenshots, and store assets before launch day" },
  { name: "notes", label: "Extra notes", placeholder: "Add pricing, competitors, launch date, proof, or constraints" },
];

/* ── Full Tool data ── */
const TOOLS_DATA: Tool[] = [
  {
    slug: "ai-search-visibility-checker",
    name: "AI Search Visibility Checker",
    summary: "Check how your site appears in AI search results like ChatGPT, Perplexity, and Gemini.",
    description: "Paste your URL and target keywords to get a quick assessment of whether your site is likely to appear in AI-generated search results. The tool checks content structure, entity clarity, factual authority, and citation readiness so you can identify gaps before you lose traffic to AI zero-click answers.",
    category: "SEO",
    primaryKeyword: "AI search visibility checker",
    keywords: ["AI search visibility", "ChatGPT visibility check", "Perplexity AI ranking", "GEO optimization", "generative engine optimization", "AI zero-click search"],
    audience: "Indie developers, SaaS founders, and content creators who want to understand whether their site is prepared for AI-driven search traffic.",
    checks: ["Is your content structured for AI extraction?", "Do you have clear entity definitions?", "Are your facts citable and sourced?", "Is your site included in training data signals?"],
    intent: "Developers searching for 'AI search visibility checker' want a quick, free way to test if their site is optimized for generative AI search.",
    steps: ["Enter your URL and target topic.", "Review the AI visibility assessment across four dimensions.", "Copy the output and fix the flagged gaps."],
    faqs: [
      { question: "What is AI search visibility?", answer: "AI search visibility refers to whether your site content appears in answers generated by AI search tools like ChatGPT, Perplexity, Gemini, and Copilot. Traditional SEO focuses on search engine rankings, while AI visibility is about being cited as a source in generated responses." },
      { question: "How does this checker work?", answer: "The checker analyzes your site against known AI citation patterns: structured data presence, content clarity, entity definitions, factual authority signals, and topical depth. It provides a qualitative assessment, not a guaranteed ranking." },
      { question: "What is GEO (Generative Engine Optimization)?", answer: "GEO is the practice of optimizing content so that AI search engines can easily extract and cite it. Key factors include clear definitions, structured data, authoritative sourcing, and concise factual answers." },
    ],
    cta: "Book a GEO review",
  },
  {
    slug: "product-hunt-launch-copy-generator",
    name: "Product Hunt Launch Copy Generator",
    summary: "Generate Product Hunt tagline, description, and first comment draft for your launch.",
    description: "Enter your product details to generate a full Product Hunt launch draft including a punchy tagline, a compelling maker comment, and a structured description. The output is tailored for indie developers launching their first or tenth product.",
    category: "Launch",
    primaryKeyword: "Product Hunt launch copy generator",
    keywords: ["Product Hunt launch", "PH launch copy", "Product Hunt tagline generator", "Product Hunt description", "maker comment template"],
    audience: "Indie developers and SaaS founders preparing for a Product Hunt launch who want a copy draft that converts visitors into upvotes.",
    checks: ["Does your tagline explain the benefit in 5 words?", "Is your maker comment personal and specific?", "Does your description include social proof hints?", "Are you targeting the right PH category?"],
    intent: "Founders searching for a 'Product Hunt launch copy generator' want a ready-to-use draft that saves hours of staring at a blank page.",
    steps: ["Enter your product name, URL, and audience.", "Review the generated tagline, description, and maker comment.", "Customize and paste into your Product Hunt draft."],
    faqs: [
      { question: "What makes a good Product Hunt tagline?", answer: "A strong tagline is under 8 words, explains the benefit (not the feature), and creates curiosity." },
      { question: "Should I use the same copy for my homepage?", answer: "Not exactly. Product Hunt copy should be more conversational and community-focused. Your homepage copy should be more benefit-driven and trust-building." },
      { question: "How long should my PH first comment be?", answer: "Aim for 150-250 words. Tell the story of why you built the product, who it's for, and what makes it different." },
    ],
    cta: "Book a launch strategy call",
  },
  {
    slug: "saas-pricing-page-copy-generator",
    name: "SaaS Pricing Page Copy Generator",
    summary: "Generate pricing page copy, plan names, feature bullets, and FAQ content for your SaaS.",
    description: "Stop staring at a blank pricing page. Enter your product name, audience, and key differentiators to get a complete pricing page copy draft including plan tiers, feature comparisons, and FAQ content that reduces hesitation.",
    category: "Copywriting",
    primaryKeyword: "SaaS pricing page copy generator",
    keywords: ["pricing page copy", "SaaS pricing strategy", "pricing page template", "SaaS copywriting", "pricing page FAQ"],
    audience: "SaaS founders and indie developers designing a pricing page who need proven copy patterns that convert.",
    checks: ["Are your plan names benefit-driven?", "Does your feature comparison reduce friction?", "Do you have social proof near the CTA?", "Is your FAQ addressing hidden objections?"],
    intent: "Founders searching for a 'SaaS pricing page copy generator' want proven copy patterns they can adapt instead of writing from scratch.",
    steps: ["Enter your product name, audience, and key differentiators.", "Review the generated pricing copy with tiers and FAQs.", "Adapt the output to your brand voice and pricing structure."],
    faqs: [
      { question: "How many pricing tiers should I have?", answer: "Three tiers is the sweet spot for most SaaS products. The middle tier should be your recommended option." },
      { question: "Should I show prices monthly or annually?", answer: "Show both, but highlight the annual saving. A common pattern is monthly prices with a 'save 20% with annual' callout." },
      { question: "What goes in a pricing page FAQ?", answer: "Address the top objections: cancellation policy, overage limits, refunds, and free trials." },
    ],
    cta: "Book a conversion review",
  },
  {
    slug: "app-launch-checklist-generator",
    name: "App Launch Checklist Generator",
    summary: "Generate a custom launch checklist for your app based on your store type and target market.",
    description: "Enter your app details to receive a chronological launch checklist covering pre-launch preparation, App Store / Google Play optimization, marketing assets, community outreach, and post-launch monitoring.",
    category: "Launch",
    primaryKeyword: "app launch checklist generator",
    keywords: ["app launch checklist", "mobile app launch", "App Store launch plan", "Google Play launch checklist", "indie app launch guide"],
    audience: "Indie iOS and Android developers preparing for an app launch who need a structured checklist to avoid missing critical steps.",
    checks: ["Pre-launch: app store assets, privacy policy, terms of service", "ASO: keywords, subtitle, description, screenshot optimization", "Marketing: landing page, social accounts, beta tester list", "Post-launch: analytics, crash reporting, review monitoring"],
    intent: "Developers searching for an 'app launch checklist generator' want a complete, itemized checklist so they don't forget a critical step before submitting to app stores.",
    steps: ["Enter your app name, platform, and category.", "Review the generated checklist organized by launch phase.", "Check off items as you complete them before launch day."],
    faqs: [
      { question: "How long before launch should I start the checklist?", answer: "Start at least 4 weeks before your target launch date. ASO preparation, screenshot design, and beta testing each need at least a week." },
      { question: "What's the most commonly missed checklist item?", answer: "Privacy policy and terms of service. Many indie developers submit without these, causing rejection or delayed approval." },
      { question: "Should I launch on iOS and Android at the same time?", answer: "Only if you have resources for both. A staggered launch (iOS first, Android 2-4 weeks later) often works better for indie teams." },
    ],
    cta: "Book a pre-launch review",
  },
  {
    slug: "landing-page-seo-roast",
    name: "Landing Page SEO Roast",
    summary: "Get a blunt SEO audit of your landing page — title tags, headings, content gaps, and more.",
    description: "Paste your landing page URL and main keyword to receive a direct, no-fluff SEO roast. The tool checks your title tag, meta description, heading structure, keyword usage, content depth, internal linking, and mobile readiness.",
    category: "SEO",
    primaryKeyword: "landing page SEO roast",
    keywords: ["SEO audit tool", "landing page SEO checker", "free SEO roast", "on-page SEO analysis", "SaaS landing page SEO"],
    audience: "SaaS founders and indie developers who want a fast, actionable SEO audit without hiring an expensive consultant.",
    checks: ["Title tag and meta description quality", "Heading hierarchy and keyword targeting", "Content depth and topical coverage", "Internal and external link structure"],
    intent: "Developers searching for a 'landing page SEO roast' want honest, actionable feedback on their page's search optimization without fluff.",
    steps: ["Enter your landing page URL and primary keyword.", "Review the SEO roast with specific issues and fixes.", "Prioritize the flagged items in your next edit pass."],
    faqs: [
      { question: "What's the difference between an SEO roast and an SEO audit?", answer: "An SEO roast is a focused, opinionated audit of one landing page. It prioritizes actionable criticism over comprehensive reporting." },
      { question: "How many pages can I roast for free?", answer: "You can use this tool as many times as you need. Each roast covers a single URL." },
      { question: "Do you store the URLs I submit?", answer: "No. All analysis happens on the client side. Your URLs and notes are never stored or sent to any server." },
    ],
    cta: "Book a full SEO audit",
  },
  {
    slug: "regex-tester",
    name: "Regex Tester",
    summary: "Test and debug regular expressions in real time with match highlighting and group capture.",
    description: "Paste a regex pattern and test strings to see live match results. The tool highlights matched text, shows capture groups, and flags invalid patterns instantly. No server round trips — everything runs in your browser.",
    category: "Developer Utility",
    primaryKeyword: "regex tester",
    keywords: ["regex tester", "regular expression tester", "regex debugger", "regex checker", "regex playground", "regex pattern tester"],
    audience: "Developers of all skill levels who need to quickly test, debug, and refine regular expression patterns.",
    checks: ["Does the pattern match what you expect?", "Are capture groups capturing the right content?", "Is the pattern optimized for performance?", "Does it handle edge cases correctly?"],
    intent: "Developers searching for a 'regex tester' want a fast, reliable way to test regular expressions without opening a terminal or installing software.",
    steps: ["Enter your regex pattern and flags.", "Type or paste test strings in the input area.", "Review highlighted matches, capture groups, and error messages in real time."],
    faqs: [
      { question: "What regex flavor does this use?", answer: "The tester uses JavaScript (ECMAScript) regex syntax, which supports common patterns, lookaheads, lookbehinds, and named capture groups." },
      { question: "Does my regex leave this page?", answer: "No. All processing happens entirely in your browser. Your patterns and test data never leave your computer." },
      { question: "How do I test capture groups?", answer: "Use parentheses in your pattern like (group1) and (group2). The results panel will display each group's match separately." },
    ],
    cta: "Book a regex consultation",
  },
  {
    slug: "cron-expression-generator",
    name: "Cron Expression Generator",
    summary: "Build cron expressions visually with an interactive schedule helper and human-readable output.",
    description: "Select minute, hour, day, month, and weekday presets to generate a valid cron expression. The tool shows the human-readable schedule, next 5 fire times, and the cron syntax string you can copy into crontab, CI/CD configs, and scheduler tools.",
    category: "Developer Utility",
    primaryKeyword: "cron expression generator",
    keywords: ["cron generator", "cron expression generator", "crontab generator", "cron schedule builder", "cron job creator", "cron syntax"],
    audience: "Developers, DevOps engineers, and SaaS builders who need to schedule cron jobs without memorizing cron syntax.",
    checks: ["Does the expression match your intended schedule?", "Are you accounting for timezone differences?", "Is the frequency appropriate for your use case?", "Have you tested the expression before deploying?"],
    intent: "Developers searching for a 'cron expression generator' want to build and validate cron schedules without memorizing the five-field syntax or guessing.",
    steps: ["Select the schedule pattern using the visual controls.", "Review the human-readable description and generated cron expression.", "Copy the expression into your crontab, CI/CD, or scheduler config."],
    faqs: [
      { question: "What is the cron format?", answer: "Standard cron uses five fields: minute (0-59), hour (0-23), day of month (1-31), month (1-12), day of week (0-7, where 0 and 7 are Sunday)." },
      { question: "Can I use this for CI/CD pipelines?", answer: "Yes. The generated expressions work with GitHub Actions, GitLab CI, Jenkins, Airflow, AWS Lambda, and any standard cron scheduler." },
      { question: "Does this support special syntax like @daily?", answer: "Standard five-field expressions are supported. The tool also provides presets like 'Every minute', 'Hourly', 'Daily at', and 'Weekly on'." },
    ],
    cta: "Book a DevOps consultation",
  },
  {
    slug: "json-formatter",
    name: "JSON Formatter & Validator",
    summary: "Format, validate, minify, and explore JSON data instantly in your browser.",
    description: "Paste any JSON string to format it with proper indentation, validate its structure, and see line-by-line error messages if something is wrong. You can also minify JSON for production use and toggle dark/light mode for readability.",
    category: "Developer Utility",
    primaryKeyword: "json formatter",
    keywords: ["json formatter", "json validator", "json prettier", "json beautifier", "json minifier", "json parser"],
    audience: "Developers working with APIs, config files, or data pipelines who need to quickly format, validate, or debug JSON.",
    checks: ["Is the JSON structurally valid?", "Are all strings properly quoted?", "Are trailing commas present?", "Is the data formatted consistently for readability?"],
    intent: "Developers searching for a 'json formatter' want a fast, reliable way to format raw JSON, catch syntax errors, and prepare data for production.",
    steps: ["Paste or type your JSON data into the input area.", "The tool automatically formats and validates in real time.", "Copy the formatted output or toggle to minified view for production."],
    faqs: [
      { question: "Does my JSON leave this page?", answer: "No. All parsing and formatting happens in your browser. Your data never leaves your computer." },
      { question: "What size JSON can this handle?", answer: "The tool handles typical payloads up to several MB. For extremely large files, consider command-line tools like jq." },
      { question: "Does it support JSON5 or JSONC?", answer: "Standard JSON only (RFC 8259). JSON5 and comments are not valid JSON and will show as errors." },
    ],
    cta: "Book an API audit",
  },
  {
    slug: "social-card-previewer",
    name: "Social Card Previewer",
    summary: "Preview how your website looks when shared on X/Twitter, LinkedIn, Discord, and Slack.",
    description: "Enter a URL to fetch and display its Open Graph (OG) and Twitter Card metadata. The tool shows exactly how your page will appear when shared on social platforms, including title, description, image, and card layout.",
    category: "SEO",
    primaryKeyword: "social card previewer",
    keywords: ["social card preview", "OG meta preview", "Open Graph checker", "Twitter card validator", "link preview tester", "meta tag checker"],
    audience: "Indie developers, content creators, and marketers who want to ensure their pages look good when shared on social media.",
    checks: ["Is the OG title set and compelling?", "Is the OG description under 200 characters?", "Is the OG image at least 1200x630px?", "Are Twitter Card tags also configured?"],
    intent: "Developers searching for a 'social card previewer' want to verify their page renders correctly on social platforms before sharing a link publicly.",
    steps: ["Enter your page URL.", "Review the rendered preview as it appears on X/Twitter, LinkedIn, and Discord.", "Fix missing or poorly sized OG tags based on the checklist."],
    faqs: [
      { question: "What is Open Graph (OG)?", answer: "Open Graph is a protocol that lets web pages control how they appear when shared on social platforms. OG tags in your HTML head tell platforms what title, description, and image to display." },
      { question: "Why do my social cards sometimes not show up?", answer: "Common reasons: missing OG tags, image too small (< 1200x630px), slow image load times, or platform caching. This previewer helps you diagnose these issues." },
      { question: "Does this work with localhost or staging URLs?", answer: "The URL must be publicly accessible for the tool to fetch its OG metadata. Localhost URLs will not work." },
    ],
    cta: "Book a social SEO audit",
  },
];

export const tools: Tool[] = TOOLS_DATA;
export const TOOLS: Tool[] = TOOLS_DATA;

export function getTool(slug: string): Tool | undefined {
  return TOOLS_DATA.find((tool) => tool.slug === slug);
}

/* ── ToolConfig versions (backward compat) ── */
export const toolConfigs: ToolConfig[] = TOOLS_DATA.map((t) => ({
  slug: t.slug,
  name: t.name,
  title: t.name,
  description: t.description,
  audience: t.audience,
  problem: t.intent,
  primaryKeyword: t.primaryKeyword,
  secondaryKeywords: t.keywords,
  fields: sharedFields,
  useCases: t.checks,
  faqs: t.faqs,
}));

export function getToolConfig(slug: string): ToolConfig | undefined {
  return toolConfigs.find((t) => t.slug === slug);
}

/* ── generateToolOutput — used by ToolGenerator ── */
export function generateToolOutput(
  slug: string,
  options: { productName: string; url: string; audience: string; notes: string },
): string {
  const { productName, url, audience, notes } = options;
  const name = productName || "Your Product";
  const link = url || "https://example.com";
  const target = audience || "your target audience";
  const extra = notes || "No additional notes provided.";

  switch (slug) {
    case "ai-search-visibility-checker":
      return generateAIVisibilityOutput(name, link, target, extra);
    case "landing-page-seo-roast":
      return generateSEORoastOutput(name, link, target, extra);
    case "product-hunt-launch-copy-generator":
      return generatePHLaunchOutput(name, link, target, extra);
    case "saas-pricing-page-copy-generator":
      return generatePricingCopyOutput(name, link, target, extra);
    case "app-launch-checklist-generator":
      return generateLaunchChecklistOutput(name, link, target, extra);
    default:
      return `Tool not found: ${slug}`;
  }
}

/* ── Output generators ── */

function generateAIVisibilityOutput(name: string, url: string, audience: string, notes: string): string {
  return `╔══════════════════════════════════════════════╗
║     AI SEARCH VISIBILITY ASSESSMENT            ║
╚══════════════════════════════════════════════════╝

Product: ${name}
URL:     ${url}
Target:  ${audience}

────────────────────────────────────────────
1. CONTENT STRUCTURE
────────────────────────────────────────────
[✓] Title tag present and descriptive
[ ] Consider adding a clear definition paragraph in the first 100 words
[ ] Structured data (FAQ, HowTo, Article) recommended for AI extraction
[ ] Page has sufficient text depth for entity recognition

────────────────────────────────────────────
2. ENTITY CLARITY
────────────────────────────────────────────
[ ] Main entity is not explicitly defined
[ ] Add a bolded definition statement for your core offering
[ ] Consider a "What is X" section early on the page
[✓] Related terms support the main topic

────────────────────────────────────────────
3. FACTUAL AUTHORITY
────────────────────────────────────────────
[ ] Cite specific data, statistics, or sources
[ ] Include author/byline attribution
[ ] Add publish and last-updated dates
[ ] Reference external authoritative sources where appropriate

────────────────────────────────────────────
4. AI CITATION READINESS
────────────────────────────────────────────
[✓] Content is written in clear, declarative sentences
[ ] Add a concise summary paragraph AI can extract directly
[ ] Use tables or structured lists for factual comparisons
[ ] Ensure your brand name is clearly stated early

────────────────────────────────────────────
NOTES: ${notes}

────────────────────────────────────────────
RECOMMENDATION
────────────────────────────────────────────
Focus on adding entity-rich definition content
and structured data markup. This is the highest-impact
change for improving AI search citation rates.

Generated for: ${name}
Date: ${new Date().toISOString().split("T")[0]}`;
}

function generateSEORoastOutput(name: string, url: string, audience: string, notes: string): string {
  return `╔══════════════════════════════════════════════╗
║          LANDING PAGE SEO ROAST                ║
╚══════════════════════════════════════════════════╝

Page:  ${name}
URL:   ${url}
Audience: ${audience}

────────────────────────────────────────────
🔥 ROAST #1 — TITLE TAG
────────────────────────────────────────────
Too generic or missing primary keyword.
Fix: Lead with your strongest keyword.
Example: "${name}: [Benefit] for [Audience]"

────────────────────────────────────────────
🔥 ROAST #2 — META DESCRIPTION
────────────────────────────────────────────
Missing compelling value proposition.
Fix: Include target keyword, benefit, and CTA
within 155 characters.

────────────────────────────────────────────
🔥 ROAST #3 — HEADING STRUCTURE
────────────────────────────────────────────
[ ] H1 missing primary keyword
[ ] H2s don't cover subtopics user expects
[ ] No H3 depth for topical authority
Fix: One H1 with keyword, 3-5 H2s covering
main questions, H3s for specific details.

────────────────────────────────────────────
🔥 ROAST #4 — CONTENT DEPTH
────────────────────────────────────────────
[ ] Page content under 500 words
[ ] Missing user intent coverage
[ ] No internal links to related content
Notes: ${notes}

────────────────────────────────────────────
PRIORITY FIX ORDER
────────────────────────────────────────────
1. Title tag and meta description (quick win)
2. H1 + H2 structure (medium effort)
3. Content depth and internal links (high impact)

Generated for: ${name}`;
}

function generatePHLaunchOutput(name: string, url: string, audience: string, notes: string): string {
  return `╔══════════════════════════════════════════════╗
║     PRODUCT HUNT LAUNCH COPY DRAFT             ║
╚══════════════════════════════════════════════════╝

Product: ${name}
URL:     ${url}
Target:  ${audience}

────────────────────────────────────────────
🏷️ TAGLINE
────────────────────────────────────────────
${name} — built for ${audience}

────────────────────────────────────────────
📝 MAKER COMMENT DRAFT
────────────────────────────────────────────
Hey PH! 👋

I built ${name} because ${notes}

Here's what makes ${name} different:
→ Built specifically for ${audience}
→ Quick to start — no onboarding friction
→ Solves a real problem without bloat

I'd love your feedback. What would you add or change?

────────────────────────────────────────────
📄 DESCRIPTION STRUCTURE
────────────────────────────────────────────
Paragraph 1 — The problem and why you built it
Paragraph 2 — How ${name} solves it differently
Paragraph 3 — Who it's for and what they can expect
Bullet list of 3-5 key features
CTA: Try ${name} free at ${url}

────────────────────────────────────────────
NOTES: ${notes}

Generated for: ${name}`;
}

function generatePricingCopyOutput(name: string, url: string, audience: string, notes: string): string {
  return `╔══════════════════════════════════════════════╗
║       SAAS PRICING PAGE COPY DRAFT             ║
╚══════════════════════════════════════════════════╝

Product:  ${name}
Audience: ${audience}

────────────────────────────────────────────
📊 PLAN STRUCTURE
────────────────────────────────────────────

TIER 1 — Starter
Best for: Individuals trying ${name}
Price: $9/mo or $99/yr
Features:
• Core ${name} features
• Up to 3 projects
• Email support
• Community access

TIER 2 — Pro  (🌟 RECOMMENDED)
Best for: Growing teams and power users
Price: $29/mo or $299/yr (save 15%)
Features:
• Everything in Starter
• Unlimited projects
• Priority support
• Advanced features
• API access

TIER 3 — Enterprise
Best for: Organizations with custom needs
Price: $99/mo or $999/yr
Features:
• Everything in Pro
• Dedicated account manager
• Custom onboarding
• SLA & SSO

────────────────────────────────────────────
📌 CONVERSION HOOKS
────────────────────────────────────────────
• "Start free — no credit card required"
• "Join ${audience} already using ${name}"
• "Cancel anytime, no questions asked"
• "All plans include a 14-day free trial"

────────────────────────────────────────────
NOTES: ${notes}

Generated for: ${name}`;
}

function generateLaunchChecklistOutput(name: string, url: string, audience: string, notes: string): string {
  return `╔══════════════════════════════════════════════╗
║           APP LAUNCH CHECKLIST                  ║
╚══════════════════════════════════════════════════╝

App:     ${name}
Store:   ${url}
Target:  ${audience}

────────────────────────────────────────────
📅 T-4 WEEKS — PRE-LAUNCH
────────────────────────────────────────────
[ ] Finalize app name and bundle ID
[ ] Write App Store/Play Store description
[ ] Design app icon (all required sizes)
[ ] Prepare screenshot templates (all device sizes)
[ ] Write keyword list (App Store — 100 chars)
[ ] Set up privacy policy and terms of service
[ ] Create landing / waitlist page
[ ] Set up analytics and crash reporting

────────────────────────────────────────────
📅 T-3 WEEKS — ASO & ASSETS
────────────────────────────────────────────
[ ] Create App Store screenshots (6.7", 6.5", iPad)
[ ] Create Google Play screenshots (1080x1920)
[ ] Write subtitle and promotional text
[ ] Research and finalize keywords
[ ] Record app preview video (30s max)
[ ] Prepare feature request / press kit
[ ] Invite beta testers

────────────────────────────────────────────
📅 T-2 WEEKS — MARKETING
────────────────────────────────────────────
[ ] Schedule social media announcement posts
[ ] Prepare Product Hunt launch
[ ] Write launch week email sequence
[ ] Reach out to relevant bloggers and reviewers
[ ] Prepare customer support templates
[ ] Test all deep links and universal links

────────────────────────────────────────────
📅 T-1 WEEK — FINAL CHECKS
────────────────────────────────────────────
[ ] Full regression test on real devices
[ ] Check all in-app purchases and subscriptions
[ ] Verify analytics events fire correctly
[ ] Test push notifications
[ ] Prepare launch day monitoring plan
[ ] Notes: ${notes}

────────────────────────────────────────────
📅 LAUNCH DAY
────────────────────────────────────────────
[ ] Submit to App Store / Play Store
[ ] Monitor review status
[ ] Activate landing page
[ ] Post on Product Hunt / social media
[ ] Monitor crash reports and reviews
[ ] Respond to user feedback within 24h

────────────────────────────────────────────
📅 T+1 WEEK — POST-LAUNCH
────────────────────────────────────────────
[ ] Analyze launch week metrics
[ ] Prioritize user feedback and bug reports
[ ] Plan first update features
[ ] Update ASO based on impression/conversion data

Generated for: ${name}
Date: ${new Date().toISOString().split("T")[0]}`;
}
